version: "3.7"
services:
#  dnscrypt:
#    environment:
#      - EXTERNAL_IP=${EXTERNAL_IP}
#    container_name: dnscrypt
#    image: jedisct1/dnscrypt-server
#    ports:
#      - 53:53
#    expose:
#      - 53
#    restart: unless-stopped
#    command: init -N onionbox.com -E ${EXTERNAL_IP}:53
  onionbox:
    build: .
    container_name: onionbox
    ports:
      - 80:80
    expose:
      - 80
#    links:
#      - dnscrypt:dnscrypt
#    dns: dnscrypt
#    dns_search: onionbox.com
#    depends_on:
#      - dnscrypt
    working_dir: /onionbox
    volumes:
      - .:/onionbox